[default]
DB_URL="sqlite:///db.sqlite"
ACCESS_TOKEN_EXPIRE_MINUTES = 60
GOOGLE_CLIENT_ID="237999433766-v5tb0omkko6je94alrjbul9bib2tpp0n.apps.googleusercontent.com"
ALGORITHM="HS256"
[development]
DB_URL=""
[production]
