[default]
DB_URL="sqlite:///db.sqlite"
ACCESS_TOKEN_EXPIRE_MINUTES = 60
GOOGLE_CLIENT_ID="237999433766-dk52to9jafu0engel53gc2spmncmo4vq.apps.googleusercontent.com"
ALGORITHM="HS256"
[development]
DB_URL=""
[production]
