[default]
DB_URL="sqlite:///db.sqlite"
ACCESS_TOKEN_EXPIRE_MINUTES = 60
GOOGLE_CLIENT_ID="237999433766-h58j1hpl1gd79qvseiekh5qnkn217blf.apps.googleusercontent.com"
ALGORITHM="HS256"
[development]
DB_URL=""
[production]
