"""made some changes

Revision ID: 8fa18a42f794
Revises: baa17baaca8a
Create Date: 2023-04-03 23:40:29.196980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fa18a42f794'
down_revision = 'baa17baaca8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('given_name', sa.String(length=100), nullable=False),
    sa.Column('family_name', sa.String(length=100), nullable=False),
    sa.Column('patronymic', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=11), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('street', sa.String(length=100), nullable=False),
    sa.Column('home', sa.String(length=100), nullable=False),
    sa.Column('flat', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('customer', sa.CHAR(36), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('material', sa.String(length=100), nullable=True),
    sa.Column('archive_path', sa.String(length=100), nullable=False),
    sa.Column('delivery_type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['customer'], ['customers.id'], name='fk_orders_customers_id_customer'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('customer')
    op.drop_table('order')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('customer', sa.CHAR(length=36), nullable=True),
    sa.Column('order_date', sa.DATE(), nullable=False),
    sa.Column('date_start', sa.DATE(), nullable=False),
    sa.Column('date_end', sa.DATE(), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.Column('material', sa.VARCHAR(length=100), nullable=False),
    sa.Column('archive_path', sa.VARCHAR(length=100), nullable=False),
    sa.Column('delivery_type', sa.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['customer'], ['customer.id'], name='fk_order_customer_id_customer'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('surname', sa.VARCHAR(length=100), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=11), nullable=False),
    sa.Column('city', sa.VARCHAR(length=100), nullable=False),
    sa.Column('street', sa.VARCHAR(length=100), nullable=False),
    sa.Column('home', sa.VARCHAR(length=100), nullable=False),
    sa.Column('flat', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('orders')
    op.drop_table('customers')
    # ### end Alembic commands ###
