"""init

Revision ID: baa17baaca8a
Revises: 
Create Date: 2023-03-26 16:03:12.246677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baa17baaca8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=11), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('street', sa.String(length=100), nullable=False),
    sa.Column('home', sa.String(length=100), nullable=False),
    sa.Column('flat', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('customer', sa.CHAR(36), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('material', sa.String(length=100), nullable=False),
    sa.Column('archive_path', sa.String(length=100), nullable=False),
    sa.Column('delivery_type', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['customer'], ['customer.id'], name='fk_order_customer_id_customer'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('customer')
    # ### end Alembic commands ###
